// backend/src/routes/categoryRoutes.js
import express from 'express';

const router = express.Router();

const categories ={
    "Algorithms": ["Approximation Algorithms", "Backtracking", "Computational Geometry", "Divide and Conquer", "Dynamic Programming", "Graph Algorithms", "Greedy Algorithms", "Network Flow Algorithms", "Parallel Algorithms", "Randomized Algorithms", "Searching Algorithms", "Sorting Algorithms", "String Algorithms"],
    "Artificial Intelligence": ["AI Algorithms", "AI Ethics", "AI in Finance", "AI in Healthcare", "AI Tools and Frameworks", "Computer Vision", "Deep Learning", "Expert Systems", "Machine Learning", "Natural Language Processing", "Neural Networks", "Reinforcement Learning", "Robotics"],
    "Augmented Reality (AR) and Virtual Reality (VR)": ["3D Modeling", "AR/VR Applications", "AR/VR Development Tools", "AR/VR Hardware", "AR/VR Software", "AR/VR User Experience", "AR/VR in Education", "AR/VR in Gaming", "AR/VR in Healthcare", "Augmented Reality SDKs", "Mixed Reality", "User Interaction in AR/VR", "Virtual Reality Environments"],
    "Big Data Analytics": ["Big Data Applications", "Big Data Tools (Hadoop, Spark)", "Data Cleaning", "Data Collection", "Data Mining", "Data Storage", "Data Transformation", "Data Visualization", "Machine Learning on Big Data", "NoSQL Databases", "Predictive Analytics", "Real-Time Analytics", "Scalable Data Processing"],
    "Bioinformatics": ["Bioinformatics Algorithms", "Biological Data Mining", "Biological Networks", "Biomedical Informatics", "Computational Drug Discovery", "Computational Genomics", "Genomic Data Analysis", "Molecular Dynamics", "Next-Generation Sequencing", "Protein Structure Prediction", "Sequence Alignment", "Structural Bioinformatics", "Systems Biology"],
    "Biometric Systems": ["Behavioral Biometrics", "Biometric Authentication", "Biometric Data Encryption", "Biometric Privacy Concerns", "Biometric Sensors", "Biometric Standards", "Biometric System Integration", "Biometric Applications", "Face Recognition", "Fingerprint Recognition", "Iris Recognition", "Multi-modal Biometrics", "Voice Recognition"],
    "Blockchain Technology": ["Blockchain Architecture", "Blockchain Development Tools", "Blockchain Platforms (Ethereum, Hyperledger)", "Blockchain Privacy", "Blockchain Scalability", "Blockchain Security", "Blockchain Use Cases", "Consensus Algorithms", "Cryptocurrencies", "Decentralized Applications (DApps)", "Smart Contracts", "Blockchain in Finance", "Blockchain in Supply Chain"],
    "Cloud Computing": ["Cloud APIs", "Cloud Management", "Cloud Native Applications", "Cloud Networking", "Cloud Security", "Cloud Service Models (IaaS, PaaS, SaaS)", "Cloud Storage", "Cloud Deployment Models (Public, Private, Hybrid)", "Containerization (Docker, Kubernetes)", "Disaster Recovery in Cloud", "Edge Computing", "Serverless Computing", "Virtualization"],
    "Computer Architecture": ["Cache Memory", "Computer Arithmetic", "Embedded Systems", "Hardware Security", "Instruction Set Architecture", "Microarchitecture", "Multicore Processors", "Parallel Processing", "Performance Evaluation", "Pipeline Processing", "Power Efficiency", "System on Chip (SoC)", "Virtual Memory"],
    "Computer Graphics": ["2D Graphics", "3D Graphics", "Computer Animation", "Computer-Aided Design", "Game Graphics", "Graphics APIs", "Graphics Hardware", "Image Synthesis", "Rendering Techniques", "Shader Programming", "Virtual Reality", "Visual Effects", "Augmented Reality"],
    "Computer Networks": ["Cloud Networking", "Internet of Things (IoT)", "Network Management", "Network Performance", "Network Protocols", "Network Security", "Network Topologies", "Routing and Switching", "Software-Defined Networking (SDN)", "TCP/IP", "Virtual Private Networks (VPN)", "Wireless Networks", "OSI Model"],
    "Computer Vision": ["3D Computer Vision", "Augmented Reality", "Computer Vision Applications", "Deep Learning for Computer Vision", "Feature Extraction", "Image Classification", "Image Processing", "Image Segmentation", "Motion Analysis", "Object Detection", "Pattern Recognition", "Visual Tracking", "Vision-Based Navigation"],
    "Computational Biology": ["Bioinformatics Algorithms", "Computational Drug Design", "Computational Genomics", "Biological Data Mining", "Biological Network Analysis", "Biomedical Data Analysis", "Drug Discovery", "Evolutionary Computation", "Genomic Data Analysis", "Machine Learning in Biology", "Molecular Dynamics", "Protein Structure Prediction", "Systems Biology"],
    "Computational Intelligence": ["Adaptive Systems", "Artificial Immune Systems", "Computational Intelligence Applications", "Computational Intelligence in Games", "Computational Intelligence in Robotics", "Evolutionary Algorithms", "Fuzzy Systems", "Genetic Programming", "Hybrid Computational Intelligence", "Neuroevolution", "Swarm Intelligence", "Ant Colony Optimization", "Computational Intelligence Tools"],
    "Cryptography": ["Cryptographic Algorithms", "Cryptographic Protocols", "Cryptographic Standards", "Cryptographic Tools", "Cryptography Applications", "Elliptic Curve Cryptography", "Hash Functions", "Public Key Cryptography", "Quantum Cryptography", "Secure Multiparty Computation", "Symmetric Key Cryptography", "Digital Signatures", "Cryptanalysis"],
    "Cybersecurity": ["Application Security", "Cryptography", "Cyber Threats", "Cybersecurity Tools", "Data Privacy", "Ethical Hacking", "Identity and Access Management", "Incident Response", "Network Security", "Risk Management", "Security Audits", "Security Policies", "Security Protocols"],
    "Data Mining": ["Anomaly Detection", "Association Rule Mining", "Classification Algorithms", "Clustering Techniques", "Data Preprocessing", "Data Warehousing", "Evaluation Metrics", "Graph Mining", "Privacy-Preserving Data Mining", "Sequential Pattern Mining", "Text Mining", "Time Series Analysis", "Web Mining"],
    "Data Structures": ["Arrays", "Disjoint Set Union", "Fenwick Trees", "Graphs", "Hash Tables", "Heaps", "Linked Lists", "Queues", "Segment Trees", "Skip Lists", "Stacks", "Tries", "Trees"],
    "Database Systems": ["Data Warehousing", "Database Design", "Database Management Systems (DBMS)", "Database Security", "Distributed Databases", "Indexing", "Normalization", "NoSQL Databases", "Query Optimization", "Relational Databases", "SQL", "Transactions", "Data Mining"],
    "Distributed Systems": ["Blockchain", "Cloud Computing", "Consistency and Replication", "Distributed Algorithms", "Distributed Computing Models", "Distributed Databases", "Distributed File Systems", "Distributed Middleware", "Distributed Storage Systems", "Fault Tolerance", "Grid Computing", "Microservices", "Peer-to-Peer Systems"],
    "Distributed Ledger Technology": ["Blockchain", "Byzantine Fault Tolerance", "Consensus Mechanisms", "Cryptographic Hashing", "Decentralization", "Directed Acyclic Graph (DAG)", "Distributed Ledger Technology Applications", "DLT in Finance", "DLT in Supply Chain", "DLT Platforms", "DLT Security", "Hashgraph", "Smart Contracts"],
    "Embedded Programming": ["Debugging Embedded Systems", "Embedded Communication Protocols", "Embedded Development Tools", "Embedded Linux", "Embedded Security", "Embedded Software", "Embedded Software Optimization", "Embedded System Design", "Firmware Development", "Interfacing with Sensors", "IoT Embedded Programming", "Microcontroller Programming", "Power Management in Embedded Systems"],
    "Embedded Systems": ["Embedded Networking", "Embedded Security", "Embedded Software", "Embedded System Applications", "Embedded System Design", "Embedded System Tools", "Firmware Development", "Hardware/Software Co-design", "IoT Devices", "Microcontrollers", "Power Management", "Real-Time Operating Systems", "Sensors and Actuators"],
    "Fault-Tolerant Computing": ["Byzantine Fault Tolerance", "Fault Injection Testing", "Fault-Tolerant Algorithms", "Fault-Tolerant Middleware", "Fault-Tolerant Operating Systems", "Hardware Redundancy", "N-Version Programming", "Recovery-Oriented Computing", "Reliability Models", "Self-Stabilization", "Software Fault Tolerance", "Failure Modes and Effects Analysis (FMEA)", "Resilient Distributed Systems"],
    "FPGA (Field-Programmable Gate Array) Design": ["ASIC Design", "Embedded FPGA", "FPGA Applications", "FPGA Design for Signal Processing", "FPGA Design Verification", "FPGA Performance Optimization", "FPGA Prototyping", "FPGA Toolchains", "FPGA in Machine Learning", "FPGA Programming", "Hardware Description Languages (VHDL, Verilog)", "High-Level Synthesis", "Logic Synthesis"],
    "Game Development": ["Artificial Intelligence in Games", "Game Audio", "Game Design", "Game Engines (Unity, Unreal)", "Game Monetization", "Game Optimization", "Game Physics", "Game Programming", "Game Testing", "Graphics in Games", "Mobile Game Development", "Multiplayer Game Development", "Virtual Reality Games"],
    "Green Computing": ["Carbon Footprint Reduction", "E-Waste Management", "Energy-Efficient Algorithms", "Energy-Efficient Computing", "Energy-Efficient Hardware Design", "Green Cloud Computing", "Green Computing Metrics", "Green Data Centers", "Green IT Standards", "Power-aware Computing", "Renewable Energy in Computing", "Sustainable IT Practices", "Environmental Impact Assessment"],
    "High-Performance Computing (HPC)": ["Cloud-Based HPC", "Distributed Memory Systems", "High-Performance Computing Applications", "High-Performance Data Analytics", "HPC Architectures", "HPC Cluster Management", "HPC Performance Tuning", "HPC Programming Models (MPI, OpenMP)", "HPC Storage Systems", "Parallel Algorithms for HPC", "Quantum Computing for HPC", "Scientific Computing", "Supercomputing"],
    "Human-Computer Interaction (HCI)": ["Assistive Technologies", "Cognitive Modeling", "HCI Design Principles", "Human Factors in HCI", "Interaction Techniques", "Mobile HCI", "Multimodal Interfaces", "Natural User Interfaces", "Usability Engineering", "User-Centered Design", "User Experience (UX)", "User Interface (UI) Design", "Virtual and Augmented Reality Interfaces"],
    "Human-Robot Interaction": ["Assistive Robotics", "Collaborative Robots", "Cognitive Robotics", "Ethics in HRI", "HRI Applications", "HRI Evaluation Methods", "HRI in Education", "HRI in Healthcare", "HRI User Studies", "Robot Design for HRI", "Robot Emotion Recognition", "Robot Learning from Demonstration", "Social Robots"],
    "Image Processing": ["Edge Detection", "Image Compression", "Image Enhancement", "Image Filtering", "Image Restoration", "Image Segmentation", "Image Transformation", "Image Watermarking", "Morphological Operations", "Object Recognition", "Pattern Recognition", "Texture Analysis", "Video Processing"],
    "Information Retrieval": ["Information Retrieval Models", "Information Retrieval Tools", "Multimedia Retrieval", "Query Processing", "Ranking Algorithms", "Relevance Feedback", "Search Engine Optimization (SEO)", "Search Engines", "Text Retrieval", "User Behavior Analysis", "Web Crawling", "IR Evaluation Metrics", "Natural Language Processing in IR"],
    "Information Security": ["Access Control", "Application Security", "Cryptography", "Cyber Threat Intelligence", "Data Encryption", "Incident Response", "Information Security Governance", "Intrusion Detection and Prevention", "Network Security", "Risk Management", "Security Policies", "Security Protocols", "Vulnerability Management"],
    "Information Theory": ["Channel Coding (Error Correction)", "Coding Theory", "Cryptography and Information Theory", "Entropy and Information", "Information Measures", "Information Retrieval", "Information Theory Applications", "Information Theory in Communication Systems", "Information Theory in Machine Learning", "Network Information Theory", "Quantum Information Theory", "Shannon's Theorems", "Source Coding (Data Compression)"],
    "Internet Technologies": ["Client-Side Scripting", "HTTP/HTTPS Protocols", "Internet Security", "Responsive Web Design", "RESTful APIs", "Semantic Web", "Server-Side Scripting", "Web Accessibility", "Web Content Management Systems", "Web Development Technologies", "Web Frameworks (e.g., Django, Flask)", "Web Performance Optimization", "Web Services"],
    "Machine Learning": ["Clustering", "Deep Learning", "Ensemble Methods", "Feature Engineering", "Machine Learning Algorithms", "Machine Learning Applications", "Machine Learning in Finance", "Machine Learning in Healthcare", "Model Evaluation", "Model Selection", "Neural Networks", "Supervised Learning", "Unsupervised Learning"],
    "Mobile Computing": ["Cross-Platform Mobile Development", "Mobile App Development", "Mobile Communication Technologies", "Mobile Device Management", "Mobile Operating Systems", "Mobile Security", "Mobile Sensors", "Mobile User Interfaces", "Mobile Web Development", "Pervasive Computing", "Power Management in Mobile Devices", "Wearable Computing", "Mobile Cloud Computing"],
    "Natural Language Processing": ["Deep Learning for NLP", "Language Modeling", "Machine Translation", "Named Entity Recognition", "NLP Applications", "Part-of-Speech Tagging", "Question Answering", "Sentiment Analysis", "Speech Recognition", "Text Classification", "Text Summarization", "Tokenization", "Word Embeddings"],
    "Operating Systems": ["Concurrency", "Distributed Operating Systems", "Embedded Operating Systems", "File Systems", "Memory Management", "Operating System Security", "Operating System Structures", "Process Scheduling", "Real-Time Operating Systems", "System Calls", "Virtual Memory", "Virtualization", "Operating System Design"],
    "Parallel Computing": ["Distributed Memory Systems", "Parallel Algorithms", "Parallel Architectures", "Parallel Programming Models", "Parallel Programming Paradigms", "Parallelization Techniques", "Performance Tuning", "Shared Memory Systems", "Synchronization", "Thread-Level Parallelism", "Parallel Computing Applications", "HPC and Parallel Computing", "Parallel Computing Tools"],
    "Robotics": ["Autonomous Robots", "Industrial Robotics", "Mobile Robots", "Robotic Manipulation", "Robotic Perception", "Robotic Planning", "Robot Learning", "Robot Navigation", "Robot Operating System (ROS)", "Swarm Robotics", "Humanoid Robots", "Medical Robotics", "Agricultural Robotics"],
    "Semantic Web": ["Knowledge Graphs", "Linked Data", "Ontology Engineering", "Reasoning in Semantic Web", "RDF (Resource Description Framework)", "Semantic Annotation", "Semantic Interoperability", "Semantic Search", "Semantic Web Applications", "Semantic Web Services", "Semantic Web Technologies", "SPARQL (Query Language for RDF)", "Web Ontology Language (OWL)"],
    "Software Architecture": ["Architectural Documentation", "Architectural Evaluation", "Architectural Frameworks", "Architectural Patterns", "Architectural Styles", "Cloud-Native Architecture", "Design Patterns", "Microservices", "Mobile Application Architecture", "Model-Driven Architecture", "Scalability and Performance", "Security in Software Architecture", "Service-Oriented Architecture (SOA)"],
    "Software Development": ["Agile Development", "DevOps", "Software Development Life Cycle (SDLC)", "Software Maintenance", "Software Project Management", "Software Quality Assurance", "Software Testing", "Waterfall Model", "Software Metrics", "Version Control", "Software Development Tools", "Requirements Engineering", "Extreme Programming (XP)"],
    "Software Engineering": ["Agile Methodologies", "DevOps Practices", "Extreme Programming", "Requirements Engineering", "Software Architecture", "Software Design Patterns", "Software Development Life Cycle", "Software Maintenance", "Software Project Management", "Software Quality Assurance", "Software Testing", "Version Control Systems", "Waterfall Model"],
    "Software Testing": ["Acceptance Testing", "Automated Testing", "Bug Tracking", "Integration Testing", "Performance Testing", "Quality Metrics", "Security Testing", "System Testing", "Test Management Tools", "Test-Driven Development (TDD)", "Unit Testing", "User Acceptance Testing (UAT)", "Regression Testing"],
    "VLSI Design": ["ASIC Design", "CMOS Technology", "Design for Testability", "Digital Circuit Design", "FPGA Design", "High-Speed VLSI Design", "Low Power VLSI", "VLSI Design Tools (CAD)", "VLSI Design Verification", "VLSI Fabrication", "VLSI Testing", "Analog Circuit Design", "3D IC Design"],
    "Virtualization": ["Application Virtualization", "Bare-Metal Virtualization", "Cloud Virtualization", "Containerization (Docker)", "Desktop Virtualization", "Hypervisors", "Performance in Virtualized Environments", "Virtual Machines", "Virtual Network Functions", "Virtual Storage", "Virtualization Management Tools", "Virtualization Security", "Virtualization in Data Centers"],
    "Web Development": ["Backend Development", "Content Management Systems (CMS)", "Frontend Development", "Full Stack Development", "Responsive Web Design", "RESTful APIs", "Single Page Applications (SPA)", "Web Accessibility", "Web Animation", "Web Development Frameworks", "Web Performance Optimization", "Web Security", "Web Services"],
    "Web Security": ["Browser Security", "Clickjacking", "Content Security Policy (CSP)", "Cross-Site Request Forgery (CSRF)", "Cross-Site Scripting (XSS)", "HTTPS Security", "Secure Authentication Methods", "Secure Coding Practices", "Security Headers", "Session Hijacking", "SQL Injection", "Web Application Firewalls (WAF)", "Web Security Auditing"],
    "Wearable Computing": ["Activity Trackers", "Augmented Reality Glasses", "Biometric Wearables", "Health Monitoring Devices", "Human Factors in Wearable Design", "Sensor Integration in Wearables", "Smart Textiles", "Wearable Communication Interfaces", "Wearable Computing Applications", "Wearable Computing Platforms", "Wearable Power Management", "Wearable Security and Privacy", "Wearable Technology"],
    "Wireless Networks": ["5G Networks", "Ad Hoc Networks", "Bluetooth", "Cellular Networks", "IoT and Wireless Networks", "Mobile Networks", "Wireless Communication Technologies", "Wireless Network Applications", "Wireless Network Planning", "Wireless Network Protocols", "Wireless Network Security", "Wireless Sensor Networks", "Wi-Fi"]
}

router.get('/categories', (req, res) => {
    res.json(Object.keys(categories));
});

router.get('/subcategories/:category', (req, res) => {
    const category = req.params.category;
    const subcategories = categories[category] || [];
    res.json(subcategories);
});

export default router;
